# Generated by Django 5.1.4 on 2025-02-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationdepartment',
            name='permissions',
            field=models.JSONField(blank=True, default=object, null=True),
        ),
        migrations.AlterField(
            model_name='organizationrank',
            name='permissions',
            field=models.JSONField(blank=True, default=object, null=True),
        ),
    ]
