# Generated by Django 5.1.4 on 2025-03-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organizationgoal_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationgoal',
            name='goal_type',
            field=models.CharField(choices=[('long_term', '장기 목표'), ('mid_term', '중기 목표'), ('monthly', '월별 실행 목표'), ('weekly', '주별 실행 목표')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
