# Generated by Django 5.1.4 on 2025-03-03 10:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_organizationgoal_goal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationgoal',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='organizationgoal',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
