# Generated by Django 5.1.4 on 2025-02-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_organizationdepartment_permissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='end_work_time',
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hire_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='start_work_time',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
