# Generated by Django 5.1.4 on 2025-03-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_organizationgoal_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationgoal',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='organizationgoal',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
