# Generated by Django 5.1.4 on 2025-02-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_end_work_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='end_work_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='start_work_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
