# Generated by Django 5.1.4 on 2025-02-26 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userprofile_end_work_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='departments',
            field=models.ManyToManyField(related_name='organizations', to='accounts.organizationdepartment'),
        ),
        migrations.AddField(
            model_name='organization',
            name='ranks',
            field=models.ManyToManyField(related_name='organizations', to='accounts.organizationrank'),
        ),
    ]
