# Generated by Django 5.1.4 on 2025-02-27 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_organization_departments_organization_ranks'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationuser',
            name='reason',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='organizationreason',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
