# Generated by Django 5.1.4 on 2025-03-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_organizationuser_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationdepartment',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizationuser',
            name='reason',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
