# Generated by Django 5.1.4 on 2024-12-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_projecttask'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
