# Generated by Django 5.1.4 on 2024-12-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_projecttask_end_time_projecttask_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttask',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
